Repository canonical/snapcraft, pull requests merged in 2018-03, with the labels that each got.

#1975 python plugin: find setup.py when source-subdir is used
  snapcraft/plugins/_python/_pip.py
  snapcraft/plugins/python.py
  tests/integration/plugins_python/test_python_plugin.py
  tests/integration/snaps/python-with-source-subdir/snap/snapcraft.yaml
  tests/integration/snaps/python-with-source-subdir/source-subdir/hello
  tests/integration/snaps/python-with-source-subdir/source-subdir/setup.py
  tests/unit/plugins/test_python.py
Labels: bug

#1976 elf: only consider regular files as possible ELF binaries
  snapcraft/internal/elf.py
  tests/unit/test_elf.py
Labels: bug

#1967 project_loader: improve the logic to install patchelf as a build tool
  snapcraft/internal/project_loader/_config.py
Labels: bug

#1980 elf: remove all un-primed libs from soname cache
  snapcraft/internal/elf.py
  snapcraft/internal/pluginhandler/__init__.py
  tests/unit/test_elf.py
Labels: bug

#1977 lifecycle: when priming dependencies need to be primed
  snapcraft/internal/elf.py
  snapcraft/internal/lifecycle/_runner.py
  tests/integration/general/test_library_precedence.py
Labels: bug

#1987 pluginhandler: add option to disable patchelf for a part
  schema/snapcraft.yaml
  snapcraft/internal/pluginhandler/__init__.py
  snapcraft/internal/pluginhandler/_build_attributes.py
  tests/fixture_setup.py
  tests/integration/general/test_prime.py
Labels: enhancement

#1989 elf: don't parse elf more than necessary
  snapcraft/internal/elf.py
Labels: bug

#1986 schema: add keep-execstack
  schema/snapcraft.yaml
  snapcraft/internal/mangling.py
  tests/integration/general/test_elf.py
  tests/integration/general/test_prime.py
  tests/integration/snaps/execstack/Makefile
  tests/integration/snaps/execstack/snapcraft.yaml
  tests/integration/snaps/execstack/test.c
Labels: bug

#1984 tests: update store tests user
  TESTING.md
  tests/fake_servers/api.py
  tests/fixture_setup.py
  tests/integration/__init__.py
  tests/integration/snaps/arm/snapcraft.yaml
  tests/integration/snaps/multiarch/snapcraft.yaml
  tests/integration/store/test_store_export_login.py
  tests/integration/store/test_store_login_logout.py
  tests/integration/store/test_store_register.py
  tests/integration/store/test_store_register_key.py
  tests/integration/store/test_store_registered.py
  tests/integration/store/test_store_release.py
  tests/unit/store/test_store_client.py
Labels: bug

#2000 elf: remove dead code
  snapcraft/internal/elf.py
Labels: bug

#1994 docker: add the architecture
  docker/beta.Dockerfile
  docker/bin/snapcraft-wrapper
  docker/candidate.Dockerfile
  docker/edge.Dockerfile
Labels: bug

#2004 errros: add a specific error when running commands from plugins
  snapcraft/_baseplugin.py
  snapcraft/internal/errors.py
  snapcraft/plugins/python.py
  tests/integration/general/test_after.py
  tests/unit/test_errors.py
Labels: bug

#2005 pluginhandler: special case go patchelf failures for classic confinement
  snapcraft/internal/elf.py
  snapcraft/internal/pluginhandler/__init__.py
  snapcraft/internal/pluginhandler/_patchelf.py
  tests/integration/snaps/go-gotty/snapcraft.yaml
Labels: bug

#2009 Base check for classic
  snapcraft/_options.py
  snapcraft/internal/project_loader/_parts_config.py
  tests/unit/project_loader/test_config.py
Labels: bug

#2015 docs: add execstack to HACKING.md's list of deb deps
  HACKING.md
Labels: docs

#2012 pluginhandler: only do elf checking and patching for type app
  snapcraft/internal/pluginhandler/__init__.py
  snapcraft/internal/project_loader/_parts_config.py
  tests/unit/__init__.py
  tests/unit/pluginhandler/test_patcher.py
Labels: bug

#2014 integration tests: snap tests shouldn't be arch-specific
  tests/integration/general/test_snap.py
Labels: bug

#2016 demos: use realpath in command entry for java-hello-world
  demos/java-hello-world/snap/snapcraft.yaml
Labels: bug

#2017 many: optimize retrieval of the linker version
  snapcraft/_options.py
  snapcraft/file_utils.py
  snapcraft/internal/elf.py
  snapcraft/internal/pluginhandler/_patchelf.py
  tests/unit/test_elf.py
  tests/unit/test_file_utils.py
  tests/unit/test_options.py
Labels: bug, enhancement

#2019 elf: avoid duplicating rpath entries
  snapcraft/internal/elf.py
  tests/integration/general/test_elf.py
Labels: bug

#2021 pluginhandler: only resort to elf mangling if the snap type is app
  snapcraft/internal/pluginhandler/__init__.py
Labels: bug

#1995 options: introduce Project and ProjectInfo
  setup.py
  snapcraft/__init__.py
  snapcraft/cli/_options.py
  snapcraft/internal/lxd/_containerbuild.py
  snapcraft/internal/meta/_snap_packaging.py
  snapcraft/internal/project_loader/_config.py
  snapcraft/project/__init__.py
  snapcraft/project/_project.py
  snapcraft/project/_project_info.py
  snapcraft/project/_project_options.py
  tests/fixture_setup.py
  tests/unit/plugins/test_kernel.py
  tests/unit/project_loader/test_config.py
  tests/unit/test_options.py
  tests/unit/test_target_arch.py
Labels: enhancement
