Repository canonical/snapcraft, pull requests merged in 2020-08, with the labels that each got.

#3245 specifications: minor cleanup for package-repositories
  specifications/package-repositories.org
Labels: specification

#3232 build providers: install apt-transport-https
  snapcraft/internal/build_providers/_base_provider.py
  tests/unit/build_providers/multipass/test_multipass.py
  tests/unit/build_providers/test_base_provider.py
Labels: bug

#3246 plugins v2: quote python packages argument for pip
  snapcraft/plugins/v2/python.py
  tests/spread/plugins/v2/snaps/python-hello-with-python-package-dep/snap/snapcraft.yaml
  tests/unit/plugins/v2/test_python.py
Labels: bug

#3203 experimental ros2 extension & colcon v2 plugin
  extensions/ros2/launch
  requirements.txt
  schema/snapcraft.json
  snapcraft/internal/project_loader/_extensions/ros2_foxy.py
  snapcraft/plugins/_plugin_finder.py
  snapcraft/plugins/v2/__init__.py
  snapcraft/plugins/v2/colcon.py
  specifications/ros2-extension.org
  tests/spread/plugins/v2/build-and-run-hello/task.yaml
  tests/spread/plugins/v2/snaps/colcon-ros2-foxy-rlcpp-hello/CMakeLists.txt
  tests/spread/plugins/v2/snaps/colcon-ros2-foxy-rlcpp-hello/package.xml
  tests/spread/plugins/v2/snaps/colcon-ros2-foxy-rlcpp-hello/snap/snapcraft.yaml
  tests/spread/plugins/v2/snaps/colcon-ros2-foxy-rlcpp-hello/src/hello.cpp
  tests/unit/plugins/v2/test_colcon.py
  tests/unit/project_loader/extensions/test_extensions.py
  tests/unit/project_loader/extensions/test_ros2_foxy.py
Labels: enhancement, specification

#3165 Update cmake plugin to support Ninja generator
  snapcraft/plugins/v2/cmake.py
  tests/spread/plugins/v2/build-and-run-hello/task.yaml
  tests/spread/plugins/v2/snaps/cmake-hello-ninja/CMakeLists.txt
  tests/spread/plugins/v2/snaps/cmake-hello-ninja/hello.c
  tests/spread/plugins/v2/snaps/cmake-hello-ninja/snap/snapcraft.yaml
  tests/unit/plugins/v2/test_cmake.py
Labels: enhancement

#3219 meta: detailed warnings for resolution of commands
  snapcraft/internal/common.py
  snapcraft/internal/meta/_utils.py
  snapcraft/internal/meta/command.py
  snapcraft/internal/meta/errors.py
  tests/unit/meta/test_command.py
  tests/unit/meta/test_command_mangle.py
Labels: enhancement

#3260 tools: update setuptools in environment-setup
  tools/environment-setup.sh
Labels: tooling

#3266 cli: add --enable-experimental-extensions option for expand-extensions
  snapcraft/cli/extensions.py
Labels: enhancement

#3265 colcon v2 plugin: honour http(s) proxy for stage-runtime-dependencies
  snapcraft/plugins/v2/colcon.py
  tests/unit/plugins/v2/test_colcon.py
Labels: bug
