Repository canonical/snapcraft, pull requests merged in 2020-05, with the labels that each got.

#3117 ci: setup release-drafter
  .github/release-drafter.yml
  .github/workflows/release-drafter.yml
Labels: project-health

#3114 npm v2 plugin: update doc string
  snapcraft/plugins/v2/npm.py
Labels: documentation

#3119 elf: fix string format for debug log
  snapcraft/internal/elf.py
Labels: bug

#3120 spread: only run in LXD with the google/multipass provider for repo
  tests/spread/general/package-repositories/task.yaml
Labels: tooling

#3121 spread tests: improvements for python-hello-with-stage-package-dep
  tests/spread/plugins/v2/snaps/python-hello-with-stage-package-dep/setup.py
  tests/spread/plugins/v2/snaps/python-hello-with-stage-package-dep/snap/snapcraft.yaml
Labels: bug

#3122 pluginhandler: make the build environment available to all steps
  snapcraft/internal/lifecycle/_runner.py
  snapcraft/internal/pluginhandler/__init__.py
  snapcraft/internal/pluginhandler/_part_environment.py
  snapcraft/internal/pluginhandler/_runner.py
  snapcraft/internal/project_loader/_config.py
  snapcraft/internal/project_loader/_parts_config.py
  tests/spread/plugins/v2/nil/task.yaml
  tests/spread/plugins/v2/snaps/nil-basic/snap/snapcraft.yaml
  tests/unit/pluginhandler/test_pluginhandler.py
  tests/unit/pluginhandler/test_runner.py
Labels: bug

#3123 cmake v2 plugin: configure with $SNAPCRAFT_PART_SRC
  snapcraft/plugins/v2/cmake.py
  tests/unit/plugins/v2/test_cmake.py
Labels: bug

#3124 storeapi: update api and error messages from push to upload
  snapcraft/_store.py
  snapcraft/storeapi/_metadata.py
  snapcraft/storeapi/_sca_client.py
  snapcraft/storeapi/_store_client.py
  snapcraft/storeapi/_upload.py
  snapcraft/storeapi/errors.py
  tests/unit/commands/__init__.py
  tests/unit/commands/test_upload.py
  tests/unit/commands/test_upload_metadata.py
  tests/unit/store/test_store_client.py
Labels: bug

#3125 cli: cleanup error handling
  snapcraft/cli/_errors.py
Labels: bug

#3126 pluginhandler: allow cleaning the build step
  snapcraft/internal/pluginhandler/__init__.py
  tests/spread/plugins/v1/rust/rebuild/task.yaml
  tests/spread/plugins/v1/rust/rust-toolchain/task.yaml
  tests/spread/plugins/v2/build-and-run-hello/task.yaml
  tests/spread/plugins/v2/snaps/autotools-hello/snap/snapcraft.yaml
  tests/spread/plugins/v2/snaps/cmake-hello/snap/snapcraft.yaml
  tests/spread/plugins/v2/snaps/dump-hello/snap/snapcraft.yaml
  tests/spread/plugins/v2/snaps/go-build-tags/snap/snapcraft.yaml
  tests/spread/plugins/v2/snaps/go-mod-hello/snap/snapcraft.yaml
  tests/spread/plugins/v2/snaps/make-hello/snap/snapcraft.yaml
  tests/spread/plugins/v2/snaps/meson-hello-staged-python/snap/snapcraft.yaml
  tests/spread/plugins/v2/snaps/meson-hello/snap/snapcraft.yaml
  tests/spread/plugins/v2/snaps/npm-hello/snap/snapcraft.yaml
  tests/spread/plugins/v2/snaps/python-hello-staged-python/snap/snapcraft.yaml
  tests/spread/plugins/v2/snaps/python-hello-with-python-package-dep/snap/snapcraft.yaml
  tests/spread/plugins/v2/snaps/python-hello-with-stage-package-dep/snap/snapcraft.yaml
  tests/spread/plugins/v2/snaps/python-hello/snap/snapcraft.yaml
  tests/spread/plugins/v2/snaps/rust-hello-features/snap/snapcraft.yaml
  tests/spread/plugins/v2/snaps/rust-hello/snap/snapcraft.yaml
Labels: bug

#3130 build providers: don't show an error if there are no auto-refresh changes
  snapcraft/internal/build_providers/_snap.py
  tests/unit/build_providers/test_snap.py
Labels: bug

#3133 go v1 plugin: go.mod support for 1.11 and 1.12
  snapcraft/plugins/v1/go.py
  tests/spread/plugins/v1/go/run-go-mod/task.yaml
  tests/spread/plugins/v1/go/snaps/go-mod-hello-with-env/go.mod
  tests/spread/plugins/v1/go/snaps/go-mod-hello-with-env/go.sum
  tests/spread/plugins/v1/go/snaps/go-mod-hello-with-env/main.go
  tests/spread/plugins/v1/go/snaps/go-mod-hello-with-env/snap/snapcraft.yaml
  tests/unit/plugins/v1/test_go.py
Labels: bug

#3134 cli: nicer message for status with no releases
  snapcraft/cli/store.py
  tests/unit/commands/test_status.py
Labels: bug

#2922 cli: fix push on Windows
  snapcraft/_store.py
  snapcraft/internal/cache/_snap.py
Labels: bug

#2949 cli: fix clean on Windows
  snapcraft/cli/lifecycle.py
  snapcraft/internal/repo/snaps.py
Labels: bug

#3136 appveyor: disable artifact collection
  appveyor.yml
Labels: tooling

#3135 build providers: set HOME environment variable using posix format
  snapcraft/internal/build_providers/_base_provider.py
Labels: bug

#3137 lifecycle: use snap from path to --check-skeleton
  snapcraft/internal/lifecycle/_packer.py
Labels: bug

#3141 build providers: use LXD-provided DNS by default
  snapcraft/internal/build_providers/_lxd/_lxd.py
  tests/unit/build_providers/lxd/test_lxd.py
Labels: bug

#3139 pluginhandler: run plugin commands in isolation
  snapcraft/internal/errors.py
  snapcraft/internal/pluginhandler/__init__.py
  tests/unit/test_errors.py
Labels: bug

#3145 cli: migrate upload and release to new channel-map
  snapcraft/_store.py
  snapcraft/cli/store.py
  tests/unit/commands/__init__.py
  tests/unit/commands/test_upload.py
  todo.org
Labels: maintenance

#3146 build providers: snap sw to channels if injecting
  snapcraft/internal/build_providers/_snap.py
  tests/fake_servers/snapd.py
  tests/unit/build_providers/test_snap.py
Labels: bug

#3128 extensions: pre/append_dir: support rpath tokens by not using eval
  extensions/desktop/common/desktop-exports
Labels: bug
