Repository canonical/snapcraft, pull requests merged in 2020-09, with the labels that each got.

#3271 build providers: use the releases endpoint for LXD
  snapcraft/internal/build_providers/_lxd/_images.py
  tests/unit/build_providers/lxd/test_lxd.py
Labels: enhancement

#3272 storeapi: improve to channel map docstrings
  snapcraft/storeapi/v2/channel_map.py
Labels: bug, documentation

#3259 cli: introduce set-default-track
  snapcraft/cli/store.py
  specifications/default-tracks.org
  tests/unit/commands/test_set_default_track.py
  todo.org
Labels: enhancement

#3140 specifications: environment lifecycle
  specifications/datastore-reference.org
  specifications/environment-management.org
  todo.org
Labels: specification

#3286 [legacy backport] v1 plugins: lock godep's dependencies
  snapcraft/plugins/godeps.py
  tests/unit/plugins/test_godeps.py
Labels: maintenance

#3285 v1 plugins: lock godep's dependencies
  snapcraft/plugins/v1/godeps.py
  tests/unit/plugins/v1/test_godeps.py
Labels: maintenance

#3238 db: introduce generalized datastore
  requirements.txt
  snapcraft/internal/db/__init__.py
  snapcraft/internal/db/datastore.py
  snapcraft/internal/db/errors.py
  snapcraft/internal/db/migration.py
  tests/unit/db/test_datastore.py
  tests/unit/db/test_errors.py
  tests/unit/db/test_migration.py
Labels: enhancement

#3295 specification: desktop extension font hook
  specifications/desktop-extensions-font-hook.org
  todo.org
Labels: specification

#3127 gnome extensions: multiarch bindtextdomain.so support
  extensions/desktop/common/init
  extensions/desktop/gnome/Makefile
Labels: enhancement

#3221 repo: install requested build-package versions
  snapcraft/internal/repo/_deb.py
  tests/unit/repo/test_deb.py
Labels: bug

#3277 pluginhandler: support using patchelf on strict snaps
  schema/snapcraft.json
  snapcraft/internal/errors.py
  snapcraft/internal/meta/_snap_packaging.py
  snapcraft/internal/pluginhandler/__init__.py
  snapcraft/internal/pluginhandler/_build_attributes.py
  snapcraft/internal/pluginhandler/_patchelf.py
  tests/spread/general/snaps/strict-patchelf/Makefile
  tests/spread/general/snaps/strict-patchelf/hello-strict.c
  tests/spread/general/snaps/strict-patchelf/snap/snapcraft.yaml
  tests/spread/general/strict-patchelf/task.yaml
  tests/unit/meta/test_snap_packaging.py
  tests/unit/pluginhandler/test_patcher.py
Labels: enhancement

#3241 snap packaging: fetch remote icons configured via appstream
  snapcraft/extractors/appstream.py
  snapcraft/internal/meta/_snap_packaging.py
  snapcraft/internal/project_loader/_config.py
  snapcraft/project/_sanity_checks.py
  tests/spread/general/appstream-desktop/expected_appstream-desktop.desktop
  tests/spread/general/appstream-desktop/expected_snap.yaml
  tests/spread/general/appstream-desktop/task.yaml
  tests/spread/general/appstream-remote-gfx/expected_appstream-desktop.desktop
  tests/spread/general/appstream-remote-gfx/expected_snap.yaml
  tests/spread/general/appstream-remote-gfx/task.yaml
  tests/spread/general/snaps/appstream-desktop/appstream-desktop
  tests/spread/general/snaps/appstream-desktop/io.snapcraft.appstream.desktop
  tests/spread/general/snaps/appstream-desktop/io.snapcraft.appstream.metainfo.xml
  tests/spread/general/snaps/appstream-desktop/snap/snapcraft.yaml
  tests/spread/general/snaps/appstream-desktop/snapcraft.svg
  tests/spread/general/snaps/appstream-remote-gfx/appstream-desktop
  tests/spread/general/snaps/appstream-remote-gfx/io.snapcraft.appstream.desktop
  tests/spread/general/snaps/appstream-remote-gfx/io.snapcraft.appstream.metainfo.xml
  tests/spread/general/snaps/appstream-remote-gfx/snap/snapcraft.yaml
  tests/spread/general/snaps/appstream-remote-gfx/snapcraft.svg
  tests/unit/project/test_sanity_checks.py
  tests/unit/project/test_schema.py
Labels: enhancement

#3270 Add PYTHONPATH to environment (fixes #1893262)
  extensions/desktop/gnome/launcher-specific
  tests/unit/project_loader/extensions/test_gnome_3_34.py
Labels: enhancement
