Repository canonical/snapcraft, pull requests merged in 2020-07, with the labels that each got.

#3186 Riscv64 support
  snapcraft/project/_project_options.py
  tests/unit/test_options.py
Labels: enhancement

#3200 flutter v1 plugin: pull from source-subdir if set
  snapcraft/plugins/v1/flutter.py
  tests/unit/plugins/v1/test_flutter.py
Labels: enhancement

#3201 pyinstaller: workaround pkg_resources issue
  snapcraft.spec
Labels: maintenance

#3202 build providers: fix base change warning message
  snapcraft/internal/build_providers/_base_provider.py
Labels: bug

#3205 spread tests: higher timeout for extension tests
  spread.yaml
Labels: tooling

#3206 tests: add missing asserts to python unit tests
  tests/unit/plugins/v2/test_python.py
Labels: bug

#3208 snap: set PATH for snapcraft command
  snap/snapcraft.yaml
  snapcraft/internal/build_providers/_base_provider.py
  tests/unit/build_providers/test_base_provider.py
Labels: bug

#3210 docker: install snapd dependency
  docker/beta.Dockerfile
  docker/candidate.Dockerfile
  docker/edge.Dockerfile
  docker/stable.Dockerfile
  docker/xenial-proposed.Dockerfile
Labels: bug

#3211 pluginhandler: fix stage-snaps for v2 plugins
  snapcraft/internal/pluginhandler/__init__.py
  tests/spread/general/stage_snaps/task.yaml
Labels: bug

#3209 extensions/desktop/common: add snapd gl vdpau dir to LD_LIBRARY_PATH
  extensions/desktop/common/desktop-exports
Labels: maintenance

#3213 cli: use prefix in store name registration hint
  snapcraft/cli/store.py
Labels: bug

#3214 snap: specify 'libxslt1-dev' than virtual 'libxslt-dev' build-package
  snap/snapcraft.yaml
Labels: bug

#3215 build providers: use PEP-440 compliant version comparison operator
  snapcraft/internal/build_providers/_base_provider.py
Labels: bug

#3216 build providers: tweak environment clean detection and logging
  snapcraft/internal/build_providers/_base_provider.py
Labels: bug

#3217 cmake v2 plugin: add stage to CMAKE_PREFIX_PATH
  snapcraft/plugins/v2/cmake.py
  tests/unit/plugins/v2/test_cmake.py
Labels: bug

#3220 review tools: link or copy snap to snap common
  snapcraft/internal/review_tools/_runner.py
  tests/unit/review_tools/test_runner.py
Labels: bug

#3228 review tools: fix snap link or copy path
  snapcraft/internal/review_tools/_runner.py
Labels: bug

#3227 meta: fix content slot to set content when using source key
  snapcraft/internal/meta/slots.py
  tests/unit/meta/test_slots.py
Labels: bug

#3229 errors: introduce HostToolNotFoundError exception
  snapcraft/internal/errors.py
  tests/unit/test_errors.py
Labels: enhancement

#3230 lifecycle: check for snap using shutil.which()
  snapcraft/cli/lifecycle.py
Labels: enhancement

#3226 extensions: kde-neon: use gtk3 platform theme on gtk-based DE's
  extensions/desktop/kde-neon/launcher-specific
Labels: bug

#3222 fix typo
  snapcraft/cli/lifecycle.py
Labels: bug

#3233 travis: set cla check as final stage
  .travis.yml
Labels: tooling

#3225 specifications: default tracks
  specifications/default-tracks.org
  todo.org
Labels: specification
