Repository canonical/snapcraft, pull requests merged in 2020-06, with the labels that each got.

#3153 review-tools: add --allow-classic flag for local review
  snapcraft/internal/review_tools/_runner.py
  tests/unit/review_tools/test_runner.py
Labels: bug

#3150 cli: error/warn when using sudo
  snapcraft/cli/_options.py
  snapcraft/cli/remote.py
  tests/spread/build-providers/lxd-prime-then-try/task.yaml
  tests/spread/build-providers/lxd-try/task.yaml
  tests/unit/cli/test_options.py
  tests/unit/commands/test_remote.py
Labels: bug

#3151 cli: disable --target-arch support on core20
  snapcraft/cli/lifecycle.py
  snapcraft/project/_project.py
  snapcraft/project/_sanity_checks.py
Labels: bug

#3158 spread: add snap watch
  spread.yaml
Labels: tooling

#3154 cmake v2 plugin: take source-subdir into account
  snapcraft/internal/pluginhandler/__init__.py
  snapcraft/internal/pluginhandler/_part_environment.py
  snapcraft/plugins/v2/cmake.py
  tests/spread/plugins/v2/build-and-run-hello/task.yaml
  tests/spread/plugins/v2/snaps/cmake-hello-subdir/snap/snapcraft.yaml
  tests/spread/plugins/v2/snaps/cmake-hello-subdir/subdir/CMakeLists.txt
  tests/spread/plugins/v2/snaps/cmake-hello-subdir/subdir/hello.c
  tests/unit/lifecycle/test_lifecycle.py
  tests/unit/plugins/v2/test_cmake.py
  tests/unit/project_loader/test_environment.py
Labels: bug

#3159 cli: improve sudo detection with euid check for warnings/errors
  snapcraft/cli/_options.py
  snapcraft/cli/remote.py
  tests/unit/cli/test_options.py
  tests/unit/commands/test_remote.py
Labels: bug

#3160 project loader: fix v1 plugin repository installation on host
  snapcraft/internal/project_loader/_config.py
  snapcraft/internal/project_loader/_parts_config.py
Labels: bug

#3161 npm v2 plugin: always include $SNAPCRAFT_PART_INSTALL/bin in $PATH
  snapcraft/plugins/v2/npm.py
  tests/unit/plugins/v2/test_npm.py
Labels: bug

#3163 cli: remove the hidden inspect command
  snapcraft/cli/_command_group.py
  snapcraft/cli/_runner.py
  snapcraft/cli/inspect.py
  snapcraft/internal/pluginhandler/__init__.py
  tests/unit/commands/test_inspect.py
Labels: maintenance

#3162 tests: remove scenario usage from lifecycle order
  tests/unit/lifecycle/test_order.py
Labels: maintenance

#3168 plugins: fix loading of catkin-tools
  snapcraft/plugins/_plugin_finder.py
Labels: bug

#3169 package-repositories: allow empty component list
  schema/snapcraft.json
  tests/unit/project/test_schema.py
Labels: bug

#3175 cli: restore --target-arch with warning for LXD and Multipass
  snapcraft/cli/_options.py
  snapcraft/cli/lifecycle.py
Labels: bug

#3177 repo: consider virtual pkgs for cache invalidation
  snapcraft/internal/repo/_deb.py
  snapcraft/internal/repo/apt_cache.py
  tests/spread/general/virtual-packages/task.yaml
  tests/unit/repo/test_deb.py
Labels: bug

#3181 cli: don't warn about --target-arch if target_arch is None
  snapcraft/cli/lifecycle.py
Labels: bug

#3180 build providers: nice message on bad base
  snapcraft/internal/build_providers/_lxd/_lxd.py
  snapcraft/internal/build_providers/errors.py
  tests/unit/build_providers/lxd/test_lxd.py
  tests/unit/build_providers/test_errors.py
Labels: bug

#3182 build providers: improve warning for unknown base
  snapcraft/internal/build_providers/_base_provider.py
Labels: bug

#3183 static: prepare for update to black 19.10b0
  snapcraft/plugins/v1/_ros/wstool.py
Labels: tooling

#3179 Maven plugin: improve error message when target libs are not found.
  snapcraft/plugins/v1/maven.py
Labels: bug

#3176 tools: fix environment-setup to work on aarch64
  tools/environment-setup.sh
Labels: tooling

#3185 cli: allow promoting from edge without --yes
  snapcraft/cli/store.py
  tests/unit/commands/test_promote.py
Labels: bug

#3173 cli: use snap pack instead of mksquashfs
  snapcraft/cli/lifecycle.py
  snapcraft/file_utils.py
  snapcraft/internal/lifecycle/__init__.py
  snapcraft/internal/lifecycle/_packer.py
  tests/fixture_setup/__init__.py
  tests/fixture_setup/_unittests.py
  tests/unit/__init__.py
  tests/unit/commands/__init__.py
  tests/unit/commands/test_pack.py
  tests/unit/commands/test_snap.py
  todo.org
Labels: maintenance

#3118 plugins: add support for local v2 plugins (core20)
  snapcraft/internal/pluginhandler/_plugin_loader.py
  tests/spread/plugins/v2/build-and-run-hello/task.yaml
  tests/spread/plugins/v2/snaps/local-plugin-from-base-hello/hello.c
  tests/spread/plugins/v2/snaps/local-plugin-from-base-hello/snap/plugins/x_local_plugin.py
  tests/spread/plugins/v2/snaps/local-plugin-from-base-hello/snap/snapcraft.yaml
  tests/spread/plugins/v2/snaps/local-plugin-from-nil-hello/hello.c
  tests/spread/plugins/v2/snaps/local-plugin-from-nil-hello/snap/plugins/x_local_plugin.py
  tests/spread/plugins/v2/snaps/local-plugin-from-nil-hello/snap/snapcraft.yaml
  todo.org
Labels: enhancement

#3174 link_or_copy: do not try to create hardlinks to symlinks.
  snapcraft/file_utils.py
Labels: bug

#3190 extensions: export content snap egl vendor dir
  extensions/desktop/common/desktop-exports
Labels: maintenance
