Repository canonical/snapcraft, pull requests merged in 2024-10, with the labels that each got.

#5076 docs(changelog): cherry-pick 8.3.3 and 8.3.4 release notes
  docs/reference/changelog.rst
Labels: rebase

#5073 chore: remove travis and autopkgtest
  .travis.yml
  HACKING.md
  README.md
  TESTING.md
  snapcraft/store/client.py
  snapcraft_legacy/storeapi/agent.py
  spread.yaml
  tests/legacy/unit/store/test_agent.py
  tests/spread/general/package-repositories/task.yaml
  tests/spread/plugins/v2/colcon-ros2-daemon/task.yaml
  tests/unit/store/test_client.py
  tools/brew_install_from_source.py
  tools/collect_ppa_autopkgtests_results.py
  tools/retry_autopkgtest.sh
  tools/run_ppa_autopkgtests.py
Labels: squash

#5070 docs: improve sidebar for the changelog page
  docs/reference/changelog.rst
Labels: squash

#5082 ci: allow republishing branches (#5078)
  .github/workflows/publish.yaml
Labels: squash

#5072 feat: build, sign and publish registries
  snapcraft/commands/registries.py
  snapcraft/errors.py
  snapcraft/models/assertions.py
  snapcraft/services/assertions.py
  snapcraft/services/registries.py
  snapcraft/store/client.py
  tests/unit/commands/test_registries.py
  tests/unit/models/test_assertions.py
  tests/unit/services/test_assertions.py
  tests/unit/services/test_registries.py
  tests/unit/store/test_client.py
Labels: squash

#5087 fix: allow parallel installations of signed snapcraft snaps (7.5)
  snapcraft_legacy/internal/build_providers/_snap.py
  snapcraft_legacy/internal/repo/snaps.py
  tests/legacy/unit/build_providers/test_snap.py
  tests/legacy/unit/repo/test_snaps.py
Labels: rebase

#5101 chore(merge): 8.4.2 into main
  docs/reference/changelog.rst
  requirements-devel.txt
  requirements-docs.txt
  requirements.txt
  setup.py
  snap/snapcraft.yaml
  snapcraft/commands/remote.py
  snapcraft_legacy/internal/build_providers/_snap.py
  snapcraft_legacy/internal/repo/snaps.py
  tests/legacy/fake_servers/snapd.py
  tests/legacy/unit/build_providers/test_snap.py
  tests/legacy/unit/repo/test_snaps.py
  tests/unit/commands/test_remote.py
  tests/unit/parts/plugins/test_python_plugin.py
Labels: merge

#5111 feat: use `craft-platforms` for build plans
  requirements-devel.txt
  requirements-docs.txt
  requirements.txt
  setup.py
  snapcraft/models/project.py
  tests/unit/models/test_projects.py
Labels: squash

#5127 Add kde-neon-6 to schema
  schema/snapcraft.json
Labels: squash

#5124 build(deps): bump craft-archives
  requirements-devel.txt
  requirements-docs.txt
  requirements.txt
  tests/spread/core24/package-repositories/task.yaml
  tests/spread/core24/package-repositories/test-key-conflict/snapcraft.yaml
Labels: squash

#5134 chore(merge): 8.4.4 into main
  docs/reference/changelog.rst
  requirements-devel.txt
  requirements-docs.txt
  requirements.txt
  setup.py
  snapcraft/models/project.py
  tests/spread/core24-suites/environment/test-variables/task.yaml
  tests/spread/core24/package-repositories/task.yaml
  tests/spread/core24/package-repositories/test-key-conflict/snapcraft.yaml
  tests/unit/models/test_projects.py
Labels: merge
