Repository canonical/snapcraft, pull requests merged in 2024-06, with the labels that each got.

#4838 chore(merge): '8.2.10' into 'main'
  docs/requirements.txt
  requirements-devel.txt
  requirements.txt
  snapcraft/commands/remote.py
  tests/unit/commands/test_remote.py
Labels: merge

#4830 refactor: migrate commands to craft-application
  docs/reference/commands.rst
  snapcraft/application.py
  snapcraft/cli.py
  snapcraft/commands/__init__.py
  snapcraft/commands/core22/__init__.py
  snapcraft/commands/core22/extensions.py
  snapcraft/commands/extensions.py
  snapcraft/commands/init.py
  snapcraft/commands/lifecycle.py
  snapcraft/commands/plugins.py
  snapcraft/commands/unimplemented.py
  snapcraft/const.py
  snapcraft/parts/yaml_utils.py
  tests/spread/core24/try/snapcraft.yaml
  tests/spread/core24/try/task.yaml
  tests/spread/general/init/task.yaml
  tests/spread/general/pack/task.yaml
  tests/spread/providers/use-lxd/task.yaml
  tests/unit/commands/test_discovery.py
  tests/unit/commands/test_expand_extensions.py
  tests/unit/commands/test_init.py
  tests/unit/commands/test_lifecycle.py
  tests/unit/commands/test_list_extensions.py
  tests/unit/commands/test_plugins.py
  tests/unit/commands/test_remote.py
  tests/unit/parts/test_parts.py
  tests/unit/test_application.py
  tools/docs/gen_cli_docs.py
Labels: squash

#4852 chore(merge): '8.2.11' into 'main'
  snapcraft/application.py
  tests/spread/core24/dotnet/snapcraft.yaml
  tests/spread/core24/dotnet/task.yaml
  tests/spread/plugins/craft-parts/build-and-run-hello/dotnet-hello/dotnet.csproj
  tests/spread/plugins/craft-parts/build-and-run-hello/dotnet-hello/hello.cs
  tests/spread/plugins/craft-parts/build-and-run-hello/dotnet-hello/snap/snapcraft.yaml
  tests/spread/plugins/craft-parts/build-and-run-hello/task.yaml
  tests/unit/conftest.py
  tests/unit/test_application.py
Labels: merge

#4855 ci: enable TiCS integration
  .github/workflows/tics.yaml
  tox.ini
Labels: rebase

#4872 chore(merge): '8.2.12' into 'main'
  .readthedocs.yaml
  docs/reference/plugins.rst
  docs/requirements.txt
  requirements-devel.txt
  requirements.txt
  setup.cfg
  setup.py
  snapcraft/application.py
  tests/spread/core24/package-filter/snapcraft.yaml
  tests/spread/core24/package-filter/task.yaml
  tests/unit/test_application.py
Labels: merge
