Repository canonical/snapcraft, pull requests merged in 2025-07, with the labels that each got.

#5593 build(deps): update craft-application to 5.4.0
  pyproject.toml
  uv.lock
Labels: run-manual-spread

#5619 docs: finalize 8.10.2 release notes
  docs/release-notes/snapcraft-8-10.rst
Labels: PR: Squash

#5620 chore(merge): 8.10.2 into main
  docs/conf.py
  docs/explanation/cryptography.rst
  docs/explanation/parts-lifecycle.rst
  docs/how-to/crafting/override-the-default-build.rst
  docs/how-to/debugging/debug-a-snap.rst
  docs/how-to/integrations/index.rst
  docs/reference/plugins.rst
  docs/reference/plugins/colcon_plugin.rst
  docs/reference/plugins/matter_sdk_plugin.rst
  docs/reference/project-file/anatomy-of-snapcraft-yaml.rst
  docs/release-notes/snapcraft-8-10.rst
  pyproject.toml
  snapcraft/extensions/gnome.py
  snapcraft/parts/plugins/_ros.py
  snapcraft/templates/test/spread.yaml.j2
  snapcraft/templates/test/spread/.extension
  snapcraft_legacy/plugins/v2/_ros.py
  tests/spread/core24/craft-test/spread/.extension
  tests/spread/core24/init-test/task.yaml
  tests/unit/extensions/test_gnome.py
  uv.lock
Labels: PR: Merge
