Repository canonical/snapcraft, pull requests merged in 2025-02, with the labels that each got.

#5242 feat: rename registries to confdbs
  docs/reference/commands.rst
  snapcraft/cli.py
  snapcraft/commands/__init__.py
  snapcraft/commands/confdbs.py
  snapcraft/errors.py
  snapcraft/models/__init__.py
  snapcraft/models/assertions.py
  snapcraft/services/__init__.py
  snapcraft/services/assertions.py
  snapcraft/services/confdbs.py
  snapcraft/services/service_factory.py
  snapcraft/store/client.py
  tests/spread/store/confdbs/editor.sh
  tests/spread/store/confdbs/task.yaml
  tests/spread/store/registries/editor.sh
  tests/unit/commands/test_confdbs.py
  tests/unit/conftest.py
  tests/unit/models/test_assertions.py
  tests/unit/services/test_confdbs.py
  tests/unit/store/test_client.py
Labels: rebase

#5246 chore(merge): 8.6.1 into main
  docs/explanation/remote-build.rst
  docs/reference/changelog.rst
  requirements-devel.txt
  requirements-docs.txt
  requirements.txt
  setup.py
Labels: merge

#5260 chore(merge): 8.6.2 into main
  docs/reference/changelog.rst
  pyproject.toml
  uv.lock
Labels: merge

#5264 fix: correct git errors in flutter plugin
  docs/release-notes/snapcraft-8-7.rst
  snapcraft/parts/plugins/flutter_plugin.py
  tests/unit/parts/plugins/test_flutter_plugin.py
Labels: squash
